// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.proto

package cn.rentaotao.common.proto;

public interface MsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.rentaotao.grpc.proto.Msg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string content = 2;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 2;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
