// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.proto

package cn.rentaotao.common.proto;

public final class MsgProto {
  private MsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_rentaotao_grpc_proto_Msg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_rentaotao_grpc_proto_Msg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tMsg.proto\022\027cn.rentaotao.grpc.proto\"\"\n\003" +
      "Msg\022\n\n\002id\030\001 \001(\r\022\017\n\007content\030\002 \001(\t2S\n\007Gree" +
      "ter\022H\n\010sayHello\022\034.cn.rentaotao.grpc.prot" +
      "o.Msg\032\034.cn.rentaotao.grpc.proto.Msg\"\000B\014B" +
      "\010MsgProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_rentaotao_grpc_proto_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_rentaotao_grpc_proto_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_rentaotao_grpc_proto_Msg_descriptor,
        new java.lang.String[] { "Id", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
